version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.8.1
    ports:
      - 5005:5005
    volumes:
      - ./backend/rasa:/app
    command: run
  server:
    build: ./backend/server
    restart: on-failure
    volumes:
      - ./backend/server:/usr/src/app
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 --log-level=info manage:app
  web:
    build: ./frontend
    restart: on-failure
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: npm start
