version: '3.0'
services:
  server:
    build: ./backend/flask
    volumes:
      - ./backend/flask:/app
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 --capture-output app:app
  web:
    build: ./frontend
    restart: on-failure
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    command: npm start
