version: '3.0'
services:
  server:
    build: ./backend/flask
    volumes:
      - ./backend/flask:/app
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    command: gunicorn --bind 0.0.0.0:5000 app:app
  web:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 80:80
    command: npm start
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
