version: '3.0'
services:
  server:
    build: ./backend/flask
    restart: on-failure
    volumes:
      - ./backend/flask:/app
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 --log-level=info server:app
  web:
    build: ./frontend
    restart: on-failure
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
    command: npm start
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
      - web
    logging:
      driver: none
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: none
