version: '3.0'
services:
  rasa:
    build: ./backend/rasa
    volumes:
      - ./backend/rasa:/app
    ports:
      - 5005:5005
    command: run --enable-api --log-file out.log
  server:
    build: ./backend/server
    restart: on-failure
    volumes:
      - ./backend/server:/usr/src/app
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 --log-level=info manage:app
  web:
    build: ./frontend/api
    restart: on-failure
    volumes:
      - ./frontend/api:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: npm start
  react:
    build: ./frontend/react
    restart: on-failure
    volumes:
      - ./frontend/react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    command: npm start
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: "none"
