from goals.base import *
from goals.input import *
from goals.actions import *
from goals.variable import *
from goals.lists import *
from goals.klass import *
from goals.procedure import *
from goals.say import *
from goals.greet import *
from goals.conditional import *
from goals.loop import *
from goals.edit import *
from goals.sound import *
from goals.execution import *
